language: ruby
os:
  - linux
script: "rspec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ree
env: "CODECLIMATE_REPO_TOKEN=ce41872e2a5a6113de9ae79a83e48c01b53bd8aea3fb1b9cf93d18d1e82c4eb1"