language: ruby
os: linux
rvm:
  - 2.1.2
addons:
	code_climate:
		repo_token:
			secure: "HN9pLM7gVvtWwFGLpCrOjrBo3q//wHa2bq+AKPYtAEFtlHehS74fyNbLRm/7m3YGn8p3GSAwHPvz0cawxLEmR2zZGwgl8GJbpkgHhsN/FEeZeohnvCnOWlYssXml2s6Zw/WkX+NdclyposfmBS0IHWBaG5lDrC3BQHUbYu3Vn8o="